services:
  foodie-connect-backend:
    image: ${DOCKER_REGISTRY-}foodieconnectbackend
    build:
      context: .
      dockerfile: foodie-connect-backend/Dockerfile
    depends_on:
      - postgres
  
  postgres:
    image: postgres:16.4
    container_name: foodie-connect-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
        - "5432:5432"
    volumes:
        - foodie-data:/var/lib/postgresql/data 
     
volumes:
  foodie-data:
  foodie-cache: